# Generated by Django 4.2.26 on 2026-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_e1ec1a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['institutional_id'], name='users_user_institu_a85759_idx'),
        ),
    ]
