# Generated by Django 5.2.6 on 2026-03-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parentstudentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Email or username attempted', max_length=255)),
                ('is_admin_attempt', models.BooleanField(default=False, help_text='True if attempt was on admin login page')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_faile_created_152913_idx'), models.Index(fields=['is_admin_attempt'], name='users_faile_is_admi_1385ec_idx')],
            },
        ),
    ]
