# Generated by Django 4.2.26 on 2026-04-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_department'),
        ('users', '0004_failed_login_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_contact',
            field=models.CharField(blank=True, help_text='Parent/guardian phone number (students only)', max_length=20),
        ),
        migrations.AddField(
            model_name='userauthmethod',
            name='secondary_method',
            field=models.CharField(blank=True, choices=[('face', 'Facial Recognition'), ('fingerprint', 'Fingerprint'), ('rfid', 'RFID Card')], help_text='Secondary method — confirms identity (blank = single-factor)', max_length=20),
        ),
        migrations.AlterField(
            model_name='userauthmethod',
            name='method',
            field=models.CharField(choices=[('face', 'Facial Recognition'), ('fingerprint', 'Fingerprint'), ('rfid', 'RFID Card')], default='rfid', help_text='Primary method — identifies the user', max_length=20),
        ),
        migrations.CreateModel(
            name='UniversityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional info from university registry')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_records', to='attendance.department')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
    ]
