# Generated by Django 4.2.26 on 2026-02-14 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_accesslog_attendance__accesse_02aaf6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_recognition_enabled', models.BooleanField(default=False, help_text='Enable facial recognition globally')),
                ('fingerprint_enabled', models.BooleanField(default=False, help_text='Enable fingerprint authentication globally')),
                ('rfid_enabled', models.BooleanField(default=True, help_text='Enable RFID authentication globally')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=10, help_text='Auto-logout after N minutes of inactivity (SEC-4)')),
                ('max_failed_attempts', models.PositiveIntegerField(default=3, help_text='Lock account after N consecutive failures')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(choices=[('raspberry_pi', 'Raspberry Pi'), ('fingerprint_sensor', 'Fingerprint Sensor'), ('rfid_reader', 'RFID Reader'), ('camera', 'Camera (Face Recognition)')], max_length=30)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('degraded', 'Degraded')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='attendance.location')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='dashboard_s_status_052ae9_idx'), models.Index(fields=['device_type'], name='dashboard_s_device__89903c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('threshold_pct', models.PositiveIntegerField(help_text='Alert when attendance % falls below this value (0-100)')),
                ('time_window', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='attendance.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'time_window'], name='dashboard_a_is_acti_cd0f70_idx')],
            },
        ),
    ]
