# Generated by Django 4.2.26 on 2026-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['accessed_at', 'success'], name='attendance__accesse_02aaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['marked_at'], name='attendance__marked__aa864c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'marked_at'], name='attendance__user_id_07a0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['location', 'marked_at'], name='attendance__locatio_e2657e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['ended_at'], name='attendance__ended_a_39f3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['-started_at'], name='attendance__started_c49520_idx'),
        ),
    ]
