# Generated by Django 4.2.26 on 2026-02-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_face_rfid_prereqs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__status_741eb8_idx',
            old_name='attendance_a_status_9d4f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingrfidscan',
            new_name='attendance__session_b3195a_idx',
            old_name='attendance_p_session_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingrfidscan',
            new_name='attendance__scanned_d72952_idx',
            old_name='attendance_p_scanned_8c1e2a_idx',
        ),
    ]
