# Generated by Django 4.2.26 on 2026-02-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_timetableslot_and_session_slot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timetableslot',
            new_name='attendance__profess_988795_idx',
            old_name='attendance_t_profess_8a0b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='timetableslot',
            new_name='attendance__locatio_2b5849_idx',
            old_name='attendance_t_locatio_9c1d4e_idx',
        ),
    ]
