# Generated by Django 5.2.6 on 2026-03-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_attendance_t_profess_8a0b2a_idx_attendance__profess_988795_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='All locations used for this course (lecture classroom, lab, etc.). Use Timetable to assign which location per slot.', related_name='courses_using', to='attendance.location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary/default location (e.g. main classroom).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='attendance.location'),
        ),
    ]
