# Generated by Django 4.2.26 on 2026-04-27 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alertrule_course_and_location_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0009_course_locations_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='locations',
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='attendance.location'),
        ),
        migrations.CreateModel(
            name='FingerprintSensorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_position', models.PositiveSmallIntegerField(help_text='Slot ID in fingerprint sensor flash memory (0-127)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_slots', to='dashboard.systemdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint sensor slot',
                'verbose_name_plural': 'Fingerprint sensor slots',
                'indexes': [models.Index(fields=['device', 'slot_position'], name='attendance__device__900645_idx')],
                'unique_together': {('device', 'slot_position')},
            },
        ),
    ]
